IMAGE_WIDTH = 100
IMAGE_HEIGHT = 50
IMAGE_CHANNELS = 3
IMAGE_FLIP_PROBABILITY = 0.5
DATASET_PATH = "H:/UNI/CS/Year3/Project/Dataset/GRID/datasets"
VIDEO_PATH = "H:/UNI/CS/Year3/Project/Dataset/GRID/video"